// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdbhaexibmbeakqpvrhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkYmhhZXhpYm1iZWFrcXB2cmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTA2MzQsImV4cCI6MjA3NTE2NjYzNH0.kONV2F-fBSByJN6k0TsbdT_yJcubPVfX3eMY0C3Eqfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});